package tlscfg

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"path/filepath"
	"testing"
	"time"
)

func TestAutoGenerateCreatesCertAndKey(t *testing.T) {
	dir := t.TempDir()
	cfg := Config{
		AutoCert: true,
		DataDir:  dir,
	}
	m, err := NewManager(context.Background(), cfg)
	if err != nil {
		t.Fatal(err)
	}
	defer m.Stop()
	certPath := filepath.Join(dir, "tls", "server.crt")
	keyPath := filepath.Join(dir, "tls", "server.key")
	if !fileExists(certPath) || !fileExists(keyPath) {
		t.Fatal("expected pem files")
	}
}

func TestLoadExistingCertificate(t *testing.T) {
	dir := t.TempDir()
	cfg := Config{AutoCert: true, DataDir: dir}
	m1, err := NewManager(context.Background(), cfg)
	if err != nil {
		t.Fatal(err)
	}
	m1.Stop()
	cfg2 := Config{
		CertFile: m1.cfg.CertFile,
		KeyFile:  m1.cfg.KeyFile,
		AutoCert: false,
	}
	m2, err := NewManager(context.Background(), cfg2)
	if err != nil {
		t.Fatal(err)
	}
	defer m2.Stop()
	if len(m2.cert.Certificate) == 0 {
		t.Fatal("expected loaded cert chain")
	}
}

func TestErrorWhenNoCertAndAutoDisabled(t *testing.T) {
	dir := t.TempDir()
	_, err := NewManager(context.Background(), Config{
		CertFile: filepath.Join(dir, "missing.crt"),
		KeyFile:  filepath.Join(dir, "missing.key"),
		AutoCert: false,
	})
	if err == nil {
		t.Fatal("expected error")
	}
}

func TestAutoGeneratedCertIncludesLoopbackIPs(t *testing.T) {
	dir := t.TempDir()
	m, err := NewManager(context.Background(), Config{AutoCert: true, DataDir: dir})
	if err != nil {
		t.Fatal(err)
	}
	defer m.Stop()
	if len(m.cert.Certificate) == 0 {
		t.Fatal("empty cert chain")
	}
	leaf, err := x509.ParseCertificate(m.cert.Certificate[0])
	if err != nil {
		t.Fatal(err)
	}
	var hasV4, hasV6 bool
	for _, ip := range leaf.IPAddresses {
		if ip.String() == "127.0.0.1" {
			hasV4 = true
		}
		if ip.String() == "::1" {
			hasV6 = true
		}
	}
	if !hasV4 || !hasV6 {
		t.Fatalf("expected 127.0.0.1 and ::1 in IP SANs, got %#v", leaf.IPAddresses)
	}
}

func TestTLSConfigMinVersionAndCipher(t *testing.T) {
	dir := t.TempDir()
	m, err := NewManager(context.Background(), Config{AutoCert: true, DataDir: dir})
	if err != nil {
		t.Fatal(err)
	}
	defer m.Stop()
	tc := m.TLSConfig()
	if tc.MinVersion != tls.VersionTLS12 {
		t.Fatalf("min version %x", tc.MinVersion)
	}
	if len(tc.CipherSuites) == 0 {
		t.Fatal("expected cipher suites")
	}
	if len(tc.CurvePreferences) == 0 {
		t.Fatal("expected curves")
	}
	_ = time.Now()
}
